<?
return array(
	'管理中心'=>array(
		'管理中心'=>array(
			array('管理中心首页','../Admin/main.html')
		)
	),
	'CMS系统'=>array(
		'新闻资讯'=>array(
			//array('文章分类','../News/news_catelist.html'),
			//array('添加文章分类','../News/addcatenews.html'),
			array('资讯列表','../News/nlist.html'),
			array('添加资讯','../News/add.html')
		),
		'专题报道'=>array(
			//array('文章分类','../News/news_catelist.html'),
			//array('添加文章分类','../News/addcatenews.html'),
			array('球星球鞋','../Star/nlist.html'),
			array('名人堂','../Celebrity/nlist.html')
		)
	),
	'活动特讯'=>array(
		'厂商活动'=>array(
			//array('文章分类','../News/news_catelist.html'),
			//array('添加文章分类','../News/addcatenews.html'),
			array('厂商活动列表','../Event/nlist.html')
		),
		'投票活动'=>array(
			//array('文章分类','../News/news_catelist.html'),
			//array('添加文章分类','../News/addcatenews.html'),
			array('投票活动列表','../Event/vote_list.html'),
		),
		'竞拍活动'=>array(
			//array('文章分类','../News/news_catelist.html'),
			//array('添加文章分类','../News/addcatenews.html'),
			array('竞拍活动列表','../Event/auction_list.html'),
		)
		
	),
	'视觉精选'=>array(
		'视频管理'=>array(
			array('videos列表','/Root/Vedio/nlist.html'),
		),
		'图片管理'=>array(
			array('photos列表','/Root/Photo/nlist.html'),
		)
	),
	'球鞋博物馆'=>array(
		'基本属性'=>array(
			array('品牌','/Root/Shoe/brand_list.html'),
			array('系列','/Root/Shoe/series_list.html'),
			array('类型','/Root/Shoe/cate_list.html'),
			array('性别','/Root/Shoe/sex_list.html'),
			array('球鞋科技','/Root/Shoe/tec_list.html'),
		),
		'球鞋博览'=>array(
			array('列表','/Root/Shoe/shoe_list.html'),
			array('添加','/Root/Shoe/shoe_add.html'),
		),
	),
	'团购专区'=>array(
		'商品'=>array(
			array('热卖中','/Root/Shopping/shoe_list.html?cate=2'),
			array('等待上架','/Root/Shopping/shoe_list.html?cate=1'),
			array('过期商品','/Root/Shopping/shoe_list.html?cate=3'),
			array('添加商品','/Root/Shopping/shoe_add.html'),
		),
		'订单'=>array(
			array('完成支付','/Root/Shopping/order_list.html?ispay=1'),
			array('尚未支付','/Root/Shopping/order_list.html?ispay=0'),
		),
	),
	'用户管理'=>array(
		'用户管理'=>array(
			array('列表','/Root/Member/nlist.html'),
		),
	),
	/*
	'商品管理'=>array(
		'商品管理'=>array(
			array('商品列表','../Goods/goods_list.html'),
			array('商品添加','../Goods/addgoods.html?goods=add'),
			array('商品分类','../Goods/cate_list.html'),
			array('添加商品分类','../Goods/addcate.html?cate=add'),
			array('品牌列表','../Goods/brand_list.html'),
			array('添加商品品牌','../Goods/addbrand.html?brand=add')
		)
	),
	'订单管理'=>array(
		'订单管理'=>array(
			array('订单列表','../Order/order_list.html'),
			array('订单查询','../Order/seekorder.html'),
			array('订单明细','../Order/detailorder.html')
		)
	),
	*/
	'管理员'=>array(
		'管理中心'=>array(
			array('管理员列表','admin_lists.html'),
			array('管理员添加','admin_add.html')
		)
	),
	/*
	'广告监控统计'=>array(
		'广告监控统计'=>array(
			array('统计查询','left.php?page_1')
		)
	)
	*/
)
?>